In [1]:

%run "./03_EMS_baselines.ipynb"

%run "./02_EMS_preprocessing.ipynb"
import numpy as np
import pandas as pd
import torch

from torch_geometric.data import Data

train_file = PROCESSED_DIR / "train_with_baselines.csv"
val_file = PROCESSED_DIR / "validation_with_baselines.csv"
test_file = PROCESSED_DIR / "test_with_baselines.csv"

for path in [train_file, val_file, test_file]:
    if not path.exists():
        raise FileNotFoundError(f"Fichier absent : {path}")

train_df = pd.read_csv(train_file)
val_df = pd.read_csv(val_file)
test_df = pd.read_csv(test_file)

datasets = {
    "train": train_df,
    "validation": val_df,
    "test": test_df,
}

for name, data in datasets.items():
    print(name, data.shape)

ROOT_DIR  : C:\Users\Admin\Desktop\Projet_Artemis2
DATA_FILE : C:\Users\Admin\Desktop\Projet_Artemis2\data\Artemis.csv | existe: True
RANDOM_SEED: 42 | DEVICE: cuda
CONFIGURATION DU PROJET HESS

BATTERIE ÉNERGIE
Énergie          : 13709.89 Wh
Tension          : 450.00 V
Capacité         : 30.4664 Ah
Masse            : 55.12 kg
Courant recharge : -14.00 A
Courant décharge : 28.00 A
Configuration    : 125S7P

BATTERIE PUISSANCE
Énergie          : 2987.12 Wh
Tension          : 402.60 V
Capacité         : 7.4196 Ah
Masse            : 50.02 kg
Courant recharge : -130.00 A
Courant décharge : 400.00 A
Configuration    : 122S2P

HESS
Énergie totale   : 16697.01 Wh
Masse totale     : 105.14 kg
Tension du bus   : 402.60 V
Puissance min    : -58638.00 W
Puissance max    : 173640.00 W

MODÈLES
LSTM seul        : 7 → 64 → 3
LSTM NS          : 15 → 64 → 3
GNN simple       : 12 → 32 → 1
MLP simple       : 5 → 64 → 32 → 1
MLP NS           : 17 → 64 → 32 → 1

Device           : cuda
Fichier          : C:\Users\Admin\Desktop\Projet_Artemis2\data\Artemis.csv

Configuration validée.
Dimensions : (14530, 19)

,time,speed,hasAeroForce,hasRollingForce,hasGravityForce,hasAcceleration,hasAccelerationForce,hasTotalForce,hasPower,P_EB,P_PB,P_conv,I_EB,I_PB,I_load,I_prime,SOC_EB,SOC_PB,SOC_HESS
0,1,0.0,0.0,109.87,0.0,0.0,0.0,109.87,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0
1,2,0.0,0.0,109.87,0.0,0.0,0.0,109.87,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0
2,3,0.0,0.0,109.87,0.0,0.0,0.0,109.87,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0
3,4,0.0,0.0,109.87,0.0,0.0,0.0,109.87,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0
4,5,0.0,0.0,109.87,0.0,0.0,0.0,109.87,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0

Colonnes manquantes : []
Colonnes supplémentaires : []
Valeurs manquantes : 0
Erreurs de conversion :

Series([], dtype: int64)

Valeurs infinies : 0
Lignes dupliquées : 0
Temps dupliqués : 0
Temps croissant : True
DT médian : 1.0
DT minimum : 1.0
DT maximum : 1.0
Pas de temps régulier : True
Erreur moyenne : 6.086558954327658e-15
MAE puissance  : 1.2407821959603739e-13
RMSE puissance : 4.5144916748033096e-13
Erreur maximale: 3.637978807091713e-12
Équilibre de puissance valide : True
SOC_EB violations strictes : 439
SOC_EB violations réelles  : 0
SOC_PB violations strictes : 0
SOC_PB violations réelles  : 0
SOC_EB min/max : 0.199749 1.0
SOC_PB min/max : 0.202598 1.0
SOC_EB ajustés : 439
SOC_PB ajustés : 0
Violations P_EB : 0
Violations P_PB : 0
Violations I_EB : 0
Violations I_PB : 0
Violations P_conv : 0
MAE P_EB vs V×I : 0.006657604955272979
MAE P_PB vs V×I : 0.0027196930488800094
MAE SOC_HESS : 3.0371527232069272e-06
Erreur max SOC_HESS : 0.00020621724428507293

,count,mean,std,min,25%,50%,75%,max
speed,14530.0,10.660828,8.094549,0.000000,3.055556,10.638889,17.076389,30.972222
hasAcceleration,14530.0,0.000082,0.704734,-4.080000,-0.220000,0.000000,0.280000,2.860000
hasPower,14530.0,3264.011708,10580.243967,-46000.000000,-751.550000,1053.660000,8279.350000,44230.330000
P_EB,14530.0,2715.173752,6027.407289,-6300.000000,-751.550000,466.140000,7622.510000,12600.000000
P_PB,14530.0,548.837956,6253.930256,-39700.000000,0.000000,0.000000,0.000000,43262.710000
P_conv,14530.0,285.998302,634.886901,-663.600000,-79.163250,49.100100,802.904400,1327.200000
I_EB,14530.0,6.033720,13.394238,-14.000000,-1.670100,1.035900,16.938900,28.000000
I_PB,14530.0,1.363234,15.533856,-98.609000,0.000000,0.000000,0.000000,107.458300
SOC_EB,14530.0,0.587983,0.247510,0.200000,0.364989,0.601149,0.808207,1.000000
SOC_PB,14530.0,0.770584,0.148476,0.202598,0.665434,0.778778,0.888395,1.000000
SOC_HESS,14530.0,0.620648,0.228479,0.200335,0.418099,0.638346,0.826919,1.000000

Total : 14530
Train : 7265
Validation : 3632
Test : 3633

Périodes
Train : 1 → 7265
Val   : 7266 → 10897
Test  : 10898 → 14530
Fichier complet : C:\Users\Admin\Desktop\Projet_Artemis2\data\processed\artemis_clean.csv
Train : C:\Users\Admin\Desktop\Projet_Artemis2\data\processed\train.csv
Validation : C:\Users\Admin\Desktop\Projet_Artemis2\data\processed\validation.csv
Test : C:\Users\Admin\Desktop\Projet_Artemis2\data\processed\test.csv

                  Indicateur Valeur
0                       rows  14530
1                    columns     28
2             missing_values      0
3             duplicate_rows      0
4             duplicate_time      0
5                 dt_seconds    1.0
6          regular_time_step   True
7        power_balance_mae_w    0.0
8        power_balance_max_w    0.0
9   soc_eb_strict_violations    439
10    soc_eb_real_violations      0
11  soc_pb_strict_violations      0
12    soc_pb_real_violations      0
13           soc_eb_adjusted    439
14           soc_pb_adjusted      0
15           p_eb_violations      0
16           p_pb_violations      0
17           i_eb_violations      0
18           i_pb_violations      0
19         p_conv_violations      0

Rapport enregistré : C:\Users\Admin\Desktop\Projet_Artemis2\results\tables\data_quality_report.json
train (7265, 28)
validation (3632, 28)
test (3633, 28)
Colonnes requises disponibles.

--- train ---
Pdem            n=7241 MAE=8285.013091 RMSE=12607.986316 R2=-0.5114
delta_SOC_EB    n=7241 MAE=0.000423 RMSE=0.000570 R2=-0.3043
delta_SOC_PB    n=7241 MAE=0.000854 RMSE=0.002031 R2=-0.0042

--- validation ---
Pdem            n=3608 MAE=8940.014933 RMSE=13198.047569 R2=-0.4449
delta_SOC_EB    n=3608 MAE=0.000470 RMSE=0.000610 R2=-0.4001
delta_SOC_PB    n=3608 MAE=0.001044 RMSE=0.002307 R2=-0.0075

--- test ---
Pdem            n=3609 MAE=8809.201186 RMSE=13050.956373 R2=-0.4488
delta_SOC_EB    n=3609 MAE=0.000371 RMSE=0.000524 R2=-0.2278
delta_SOC_PB    n=3609 MAE=0.001424 RMSE=0.002986 R2=-0.0460

        split        target     n          mae          rmse        r2
0       train          Pdem  7241  8285.013091  12607.986316 -0.511413
1       train  delta_SOC_EB  7241     0.000423      0.000570 -0.304273
2       train  delta_SOC_PB  7241     0.000854      0.002031 -0.004198
3  validation          Pdem  3608  8940.014933  13198.047569 -0.444931
4  validation  delta_SOC_EB  3608     0.000470      0.000610 -0.400051
5  validation  delta_SOC_PB  3608     0.001044      0.002307 -0.007520
6        test          Pdem  3609  8809.201186  13050.956373 -0.448818
7        test  delta_SOC_EB  3609     0.000371      0.000524 -0.227789
8        test  delta_SOC_PB  3609     0.001424      0.002986 -0.045978

train | non défini : 1341 (18.46 %) | moyenne : 0.111316 | min : 0.000000 | max : 0.863043
validation | non défini : 519 (14.29 %) | moyenne : 0.118508 | min : 0.000000 | max : 0.863043
test | non défini : 567 (15.61 %) | moyenne : 0.222509 | min : 0.000000 | max : 1.000000
train | valeurs valides : 5924 | hors bornes : 0
validation | valeurs valides : 3113 | hors bornes : 0
test | valeurs valides : 3066 | hors bornes : 0
Baselines enregistrées.
train_with_baselines.csv | existe : True
validation_with_baselines.csv | existe : True
test_with_baselines.csv | existe : True
persistence_metrics.csv | existe : True
ROOT_DIR  : C:\Users\Admin\Desktop\Projet_Artemis2
DATA_FILE : C:\Users\Admin\Desktop\Projet_Artemis2\data\Artemis.csv | existe: True
RANDOM_SEED: 42 | DEVICE: cuda
CONFIGURATION DU PROJET HESS

BATTERIE ÉNERGIE
Énergie          : 13709.89 Wh
Tension          : 450.00 V
Capacité         : 30.4664 Ah
Masse            : 55.12 kg
Courant recharge : -14.00 A
Courant décharge : 28.00 A
Configuration    : 125S7P

BATTERIE PUISSANCE
Énergie          : 2987.12 Wh
Tension          : 402.60 V
Capacité         : 7.4196 Ah
Masse            : 50.02 kg
Courant recharge : -130.00 A
Courant décharge : 400.00 A
Configuration    : 122S2P

HESS
Énergie totale   : 16697.01 Wh
Masse totale     : 105.14 kg
Tension du bus   : 402.60 V
Puissance min    : -58638.00 W
Puissance max    : 173640.00 W

MODÈLES
LSTM seul        : 7 → 64 → 3
LSTM NS          : 15 → 64 → 3
GNN simple       : 12 → 32 → 1
MLP simple       : 5 → 64 → 32 → 1
MLP NS           : 17 → 64 → 32 → 1

Device           : cuda
Fichier          : C:\Users\Admin\Desktop\Projet_Artemis2\data\Artemis.csv

Configuration validée.
Dimensions : (14530, 19)

,time,speed,hasAeroForce,hasRollingForce,hasGravityForce,hasAcceleration,hasAccelerationForce,hasTotalForce,hasPower,P_EB,P_PB,P_conv,I_EB,I_PB,I_load,I_prime,SOC_EB,SOC_PB,SOC_HESS
0,1,0.0,0.0,109.87,0.0,0.0,0.0,109.87,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0
1,2,0.0,0.0,109.87,0.0,0.0,0.0,109.87,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0
2,3,0.0,0.0,109.87,0.0,0.0,0.0,109.87,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0
3,4,0.0,0.0,109.87,0.0,0.0,0.0,109.87,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0
4,5,0.0,0.0,109.87,0.0,0.0,0.0,109.87,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0

Colonnes manquantes : []
Colonnes supplémentaires : []
Valeurs manquantes : 0
Erreurs de conversion :

Series([], dtype: int64)

Valeurs infinies : 0
Lignes dupliquées : 0
Temps dupliqués : 0
Temps croissant : True
DT médian : 1.0
DT minimum : 1.0
DT maximum : 1.0
Pas de temps régulier : True
Erreur moyenne : 6.086558954327658e-15
MAE puissance  : 1.2407821959603739e-13
RMSE puissance : 4.5144916748033096e-13
Erreur maximale: 3.637978807091713e-12
Équilibre de puissance valide : True
SOC_EB violations strictes : 439
SOC_EB violations réelles  : 0
SOC_PB violations strictes : 0
SOC_PB violations réelles  : 0
SOC_EB min/max : 0.199749 1.0
SOC_PB min/max : 0.202598 1.0
SOC_EB ajustés : 439
SOC_PB ajustés : 0
Violations P_EB : 0
Violations P_PB : 0
Violations I_EB : 0
Violations I_PB : 0
Violations P_conv : 0
MAE P_EB vs V×I : 0.006657604955272979
MAE P_PB vs V×I : 0.0027196930488800094
MAE SOC_HESS : 3.0371527232069272e-06
Erreur max SOC_HESS : 0.00020621724428507293

,count,mean,std,min,25%,50%,75%,max
speed,14530.0,10.660828,8.094549,0.000000,3.055556,10.638889,17.076389,30.972222
hasAcceleration,14530.0,0.000082,0.704734,-4.080000,-0.220000,0.000000,0.280000,2.860000
hasPower,14530.0,3264.011708,10580.243967,-46000.000000,-751.550000,1053.660000,8279.350000,44230.330000
P_EB,14530.0,2715.173752,6027.407289,-6300.000000,-751.550000,466.140000,7622.510000,12600.000000
P_PB,14530.0,548.837956,6253.930256,-39700.000000,0.000000,0.000000,0.000000,43262.710000
P_conv,14530.0,285.998302,634.886901,-663.600000,-79.163250,49.100100,802.904400,1327.200000
I_EB,14530.0,6.033720,13.394238,-14.000000,-1.670100,1.035900,16.938900,28.000000
I_PB,14530.0,1.363234,15.533856,-98.609000,0.000000,0.000000,0.000000,107.458300
SOC_EB,14530.0,0.587983,0.247510,0.200000,0.364989,0.601149,0.808207,1.000000
SOC_PB,14530.0,0.770584,0.148476,0.202598,0.665434,0.778778,0.888395,1.000000
SOC_HESS,14530.0,0.620648,0.228479,0.200335,0.418099,0.638346,0.826919,1.000000

Total : 14530
Train : 7265
Validation : 3632
Test : 3633

Périodes
Train : 1 → 7265
Val   : 7266 → 10897
Test  : 10898 → 14530
Fichier complet : C:\Users\Admin\Desktop\Projet_Artemis2\data\processed\artemis_clean.csv
Train : C:\Users\Admin\Desktop\Projet_Artemis2\data\processed\train.csv
Validation : C:\Users\Admin\Desktop\Projet_Artemis2\data\processed\validation.csv
Test : C:\Users\Admin\Desktop\Projet_Artemis2\data\processed\test.csv

                  Indicateur Valeur
0                       rows  14530
1                    columns     28
2             missing_values      0
3             duplicate_rows      0
4             duplicate_time      0
5                 dt_seconds    1.0
6          regular_time_step   True
7        power_balance_mae_w    0.0
8        power_balance_max_w    0.0
9   soc_eb_strict_violations    439
10    soc_eb_real_violations      0
11  soc_pb_strict_violations      0
12    soc_pb_real_violations      0
13           soc_eb_adjusted    439
14           soc_pb_adjusted      0
15           p_eb_violations      0
16           p_pb_violations      0
17           i_eb_violations      0
18           i_pb_violations      0
19         p_conv_violations      0

Rapport enregistré : C:\Users\Admin\Desktop\Projet_Artemis2\results\tables\data_quality_report.json

c:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

train (7265, 30)
validation (3632, 30)
test (3633, 30)

Vérification des colonnes

In [2]:
required_cols = [
    TIME_COL,
    "SOC_EB",
    "SOC_PB",
    "hasPower",
    "hasAcceleration",
    "alpha_ems_eb_priority",
    "alpha_ems_eb_priority_valid",
]

for name, data in datasets.items():
    missing = sorted(
        set(required_cols) - set(data.columns)
    )

    if missing:
        raise ValueError(
            f"{name} : colonnes absentes {missing}"
        )

    if data[required_cols].isna().all(axis=0).any():
        raise ValueError(
            f"{name} contient une colonne entièrement vide."
        )

print("Colonnes validées.")

Colonnes validées.

Création des noeuds et arrets

In [3]:
NODE_INDEX = {
    name: index
    for index, name in enumerate(GNN_NODE_NAMES)
}

UNDIRECTED_EDGES = [
    ("energy_battery", "converter"),
    ("power_battery", "converter"),
    ("converter", "motor"),
    ("energy_battery", "motor"),
    ("motor", "vehicle"),
]

edge_list = []

for source, target in UNDIRECTED_EDGES:
    source_index = NODE_INDEX[source]
    target_index = NODE_INDEX[target]

    edge_list.append(
        (source_index, target_index)
    )

    edge_list.append(
        (target_index, source_index)
    )

edge_index = torch.tensor(
    edge_list,
    dtype=torch.long,
).t().contiguous()

print("Nombre de nœuds :", len(GNN_NODE_NAMES))
print("Nombre d'arêtes :", edge_index.shape[1])
print(edge_index)

Nombre de nœuds : 5
Nombre d'arêtes : 10
tensor([[0, 2, 1, 2, 2, 3, 0, 3, 3, 4],
        [2, 0, 2, 1, 3, 2, 3, 0, 4, 3]])

Parametres des noeuds

In [4]:
STATIC_FEATURES = {
    "energy_battery": {
        "current_discharge_max_a": I_EB_MAX_A,
        "capacity_ah": CAPACITY_EB_AH,
        "power_discharge_max_w": P_EB_MAX_W,
        "power_charge_max_abs_w": abs(P_EB_MIN_W),
    },
    "power_battery": {
        "current_discharge_max_a": I_PB_MAX_A,
        "capacity_ah": CAPACITY_PB_AH,
        "power_discharge_max_w": P_PB_MAX_W,
        "power_charge_max_abs_w": abs(P_PB_MIN_W),
    },
    "converter": {
        "current_discharge_max_a": (
            P_CONV_MAX_W / V_HESS_BUS_NOM
        ),
        "capacity_ah": 0.0,
        "power_discharge_max_w": P_CONV_MAX_W,
        "power_charge_max_abs_w": abs(P_CONV_MIN_W),
    },
    "motor": {
        "current_discharge_max_a": 0.0,
        "capacity_ah": 0.0,
        "power_discharge_max_w": 0.0,
        "power_charge_max_abs_w": 0.0,
    },
    "vehicle": {
        "current_discharge_max_a": 0.0,
        "capacity_ah": 0.0,
        "power_discharge_max_w": 0.0,
        "power_charge_max_abs_w": 0.0,
    },
}

Construction des caractéristiques

In [5]:
def build_raw_node_features(
    soc_eb,
    soc_pb,
    p_dem,
    acceleration,
):
    soc_values = {
        "energy_battery": soc_eb,
        "power_battery": soc_pb,
        "converter": 0.0,
        "motor": 0.0,
        "vehicle": 0.0,
    }

    continuous = []

    for node_name in GNN_NODE_NAMES:
        static = STATIC_FEATURES[node_name]

        continuous.append([
            soc_values[node_name],
            static["current_discharge_max_a"],
            static["capacity_ah"],
            static["power_discharge_max_w"],
            static["power_charge_max_abs_w"],
            p_dem,
            acceleration,
        ])

    return np.asarray(
        continuous,
        dtype=np.float32,
    )

Calcul de la normalisation

In [6]:
valid_train = (
    train_df["alpha_ems_eb_priority_valid"]
    .astype(bool)
)

train_valid_df = (
    train_df.loc[valid_train]
    .reset_index(drop=True)
)

raw_train_features = []

for row in train_valid_df.itertuples():
    features = build_raw_node_features(
        soc_eb=row.SOC_EB,
        soc_pb=row.SOC_PB,
        p_dem=row.hasPower,
        acceleration=row.hasAcceleration,
    )

    raw_train_features.append(features)

raw_train_features = np.concatenate(
    raw_train_features,
    axis=0,
)

gnn_x_mean = raw_train_features.mean(
    axis=0,
    dtype=np.float64,
).astype(np.float32)

gnn_x_std = raw_train_features.std(
    axis=0,
    dtype=np.float64,
).astype(np.float32)

if np.any(gnn_x_std < 1e-12):
    constant_features = np.array(
        GNN_CONTINUOUS_FEATURE_NAMES
    )[gnn_x_std < 1e-12]

    raise ValueError(
        f"Caractéristiques constantes : "
        f"{constant_features.tolist()}"
    )

np.savez(
    GNN_SCALER_FILE,
    x_mean=gnn_x_mean,
    x_std=gnn_x_std,
    continuous_feature_names=np.array(
        GNN_CONTINUOUS_FEATURE_NAMES
    ),
    node_names=np.array(GNN_NODE_NAMES),
)

print("Moyennes :", gnn_x_mean)
print("Écarts-types :", gnn_x_std)
print("Scalers :", GNN_SCALER_FILE)

Moyennes : [ 3.3803016e-01  8.6355095e+01  7.5771990e+00  3.5032000e+04
  1.1879600e+04  3.5836106e+03 -4.6809590e-03]
Écarts-types : [4.1979468e-01 1.5717012e+02 1.1799858e+01 6.3180293e+04 2.0366195e+04
 1.1234938e+04 7.8738546e-01]
Scalers : C:\Users\Admin\Desktop\Projet_Artemis2\models\gnn_node_scalers.npz

Encodage des noeuds

In [7]:
NODE_TYPE_ENCODING = np.eye(
    len(GNN_NODE_NAMES),
    dtype=np.float32,
)

Construction du graphes

In [8]:
def build_graph(
    soc_eb,
    soc_pb,
    p_dem,
    acceleration,
    alpha_target,
    sample_index,
    time_value,
):
    continuous = build_raw_node_features(
        soc_eb=soc_eb,
        soc_pb=soc_pb,
        p_dem=p_dem,
        acceleration=acceleration,
    )

    continuous = (
        continuous - gnn_x_mean
    ) / gnn_x_std

    node_features = np.concatenate(
        [
            continuous,
            NODE_TYPE_ENCODING,
        ],
        axis=1,
    )

    return Data(
        x=torch.tensor(
            node_features,
            dtype=torch.float32,
        ),
        edge_index=edge_index.clone(),
        y=torch.tensor(
            [alpha_target],
            dtype=torch.float32,
        ),
        sample_index=torch.tensor(
            [sample_index],
            dtype=torch.long,
        ),
        time=torch.tensor(
            [time_value],
            dtype=torch.float32,
        ),
        p_dem=torch.tensor(
            [p_dem],
            dtype=torch.float32,
        ),
    )

Construction d'un jeu du graphe

In [9]:
def build_graph_dataset(data):
    valid = (
        data["alpha_ems_eb_priority_valid"]
        .astype(bool)
    )

    selected = data.loc[valid].copy()

    graphs = []

    for index, row in selected.iterrows():
        graph = build_graph(
            soc_eb=row["SOC_EB"],
            soc_pb=row["SOC_PB"],
            p_dem=row["hasPower"],
            acceleration=row["hasAcceleration"],
            alpha_target=row["alpha_ems_eb_priority"],
            sample_index=index,
            time_value=row[TIME_COL],
        )

        graphs.append(graph)

    return graphs

Création du graphe

In [10]:
graphs_train = build_graph_dataset(
    train_df
)

graphs_val = build_graph_dataset(
    val_df
)

graphs_test = build_graph_dataset(
    test_df
)

print("Train      :", len(graphs_train))
print("Validation :", len(graphs_val))
print("Test       :", len(graphs_test))

print(graphs_train[0])
print("x :", graphs_train[0].x.shape)
print("edge_index :", graphs_train[0].edge_index.shape)
print("y :", graphs_train[0].y.shape)

Train      : 5924
Validation : 3113
Test       : 3066
Data(x=[5, 12], edge_index=[2, 10], y=[1], time=[1], sample_index=[1], p_dem=[1])
x : torch.Size([5, 12])
edge_index : torch.Size([2, 10])
y : torch.Size([1])

Controle du graphe

In [11]:
for split_name, graphs in {
    "train": graphs_train,
    "validation": graphs_val,
    "test": graphs_test,
}.items():
    if len(graphs) == 0:
        raise ValueError(
            f"Aucun graphe dans {split_name}."
        )

    for graph in graphs:
        if graph.x.shape != (
            len(GNN_NODE_NAMES),
            GNN_INPUT_DIM,
        ):
            raise ValueError(
                f"Forme incorrecte dans {split_name}."
            )

        if not torch.isfinite(graph.x).all():
            raise ValueError(
                f"Valeur non finie dans {split_name}."
            )

        if not torch.isfinite(graph.y).all():
            raise ValueError(
                f"Cible non finie dans {split_name}."
            )

        if not (
            ALPHA_MIN
            <= graph.y.item()
            <= ALPHA_MAX
        ):
            raise ValueError(
                f"Cible hors bornes dans {split_name}."
            )

print("Graphes validés.")

Graphes validés.

Sauvegarde

In [12]:
torch.save(
    {
        "train": graphs_train,
        "validation": graphs_val,
        "test": graphs_test,
        "edge_index": edge_index,
        "node_names": GNN_NODE_NAMES,
        "continuous_feature_names": GNN_CONTINUOUS_FEATURE_NAMES,
        "input_dim": GNN_INPUT_DIM,
    },
    GNN_GRAPHS_FILE,
)

print("Graphes sauvegardés :", GNN_GRAPHS_FILE)
print("Scalers sauvegardés :", GNN_SCALER_FILE)

Graphes sauvegardés : C:\Users\Admin\Desktop\Projet_Artemis2\data\processed\hess_graphs.pt
Scalers sauvegardés : C:\Users\Admin\Desktop\Projet_Artemis2\models\gnn_node_scalers.npz

Test

In [13]:
from torch_geometric.loader import DataLoader

smoke_loader = DataLoader(
    graphs_train[:16],
    batch_size=8,
    shuffle=False,
)

batch = next(iter(smoke_loader))

print("Batch x          :", batch.x.shape)
print("Batch edge_index :", batch.edge_index.shape)
print("Batch y          :", batch.y.shape)
print("Batch vector     :", batch.batch.shape)
print("Nombre graphes   :", batch.num_graphs)

Batch x          : torch.Size([40, 12])
Batch edge_index : torch.Size([2, 80])
Batch y          : torch.Size([8])
Batch vector     : torch.Size([40])
Nombre graphes   : 8